# Dependencies
markdown:         kramdown
highlighter:      rouge
# Permalinks
permalink:        pretty

# Setup
title:            pitaside
tagline:          'my thought on code'
description:      'Creativity isnt a function of man possessing knowledge it is rather a function of knowledge possessing man'
url:               https//freewayz.github.io
baseurl:          ''

author:
  name:           'Peter Edache'
  url:            https://github.com/freewayz

paginate:         1
gems: [jekyll-paginate]
version:          1.0.0

github:
  repo:           https://github.com/freewayz
social:
  - icon:	twitter
    url:	https://twitter.com/fr3wayz
    desc: Twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="


  - icon:	github
    url:	https://github.com/freewayz
    desc:	Find me on GitHub
    share_url:
    share_title:
    share_link:

