# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            pitaside
tagline:          'my thought on code'
description:      'Creativity isnt a function of man possessing knowledge it is rather a function of knowledge possessing man'
url:               http//freewayz.github.io
baseurl:          ''

author:
  name:           'Peter Edache'
  url:            https://twitter.com/freewayz

paginate:         3

gems: [jekyll-paginate]
# Custom vars
version:          1.0.0

github:
  repo:           https://twitter.com/freewayz

