# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            pitaside
tagline:          'my thought on code'
description:      'Creativity isn't a function of man possessing knowledge; it is rather a function of knowledge possessing man'
url:               http//freewayz.github.io
baseurl:          ''

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         3

gems: [jekyll-paginate]
# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon

